# Generated by Django 5.2.2 on 2026-02-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'permissions': (('can_create_book', 'Can create book'), ('can_update_book', 'Can update book'), ('can_delete_book', 'Can delete book'))},
        ),
    ]
